;; Clojure customizations
(require 'clojure-mode)
(define-clojure-indent
  (defroutes 'defun)
  (GET 2)
  (POST 2)
  (PUT 2)
  (DELETE 2)
  (HEAD 2)
  (ANY 2)
  (context 2)
  (rfn 1)
  (when-json 2)
  (when-authenticated 1)
  (when-authorized 2)
  (when-in-role 2)
  (when-enabled 1)
  (with-account 3)
  (with-identity-account 2)
  (-> 1)
  (->> 1)
  (some-> 1)
  (some->> 1)
  (cond-> 1)
  (cond->> 1)
  (as-> 2)
  (s/defrecord 1))
